### PR TITLE
Fix some minor typos and grammar

### PR DESCRIPTION
**Pull request by iggraham**
I was checking out ChaosIQ, and I'm new to the whole GitHub experience and had been wanting to try out the GitHub workflow.  I saw a couple of doc typos as I read your material and thought this might be an opportunity!

Some of these are clear simple typos, and some are grammar suggestion that you can take or not as you please.  I hope this is a help.

What you've started with ChaosIQ looks really interesting - I hope you can make a good go of it.

Cheers, Ian

### CODE REVIEW

**Comment by iggraham** [comment]
I should add there are more uses of the American spelling of "organization" than of the British "organisation", so in seeking consistency I went for the approach that involved the least change.  I wouldn't even be surprised if there is a shift that way happening gradually over there - certainly we Canadians now largely use the American spelling.  The same goes for the verb form of "to practice" rather than using the British "to practise".

**Comment by Lawouach** [comment]
Hello @iggraham, sorry for being a bit slow to respond.

Thank you so much for your first contribution here, it's great to see you made the effort and I hope it was a fun experience.

Before we are going to review your changes, I would like to add a small challenge. To be good open source citizen on these projects, we all have to sign our commits to indicate we agree with the DCO.

The DCO is a small agreement between contributors that they understand the followings:

```
By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

https://developercertificate.org/

The idea is to avoid a full contributor license agreement which is heavy and favour a lightweight approach. This ensures that you accept the terms above when you make a contribution.

Usually, we would have a [GitHub check](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks) that would have warned you but it's not been setup on this repository so you couldn't have known.

So, may I ask you to change your commit on your local copy of your fork to add the signature to the commit message?

If you haven't done any other commits since you pushed, you could try:

```
$ git commit --amend --signoff
```

This will open a text editor with your commit and a line like this:

```
Signed-off-by: NAME <EMAIL>
```

Save this and do a push back to your remote repository:

```
$ git push -f
```

This should update this PR automatically :)

Let me knwo if you need any help.

Thanks

**Comment by iggraham** [comment]
Done now Sylvain, thanks.  I hope it's okay to just use the private github email address for signing.  I'm trying to keep down the amount of junk mail I might receive.

**Comment by Lawouach** [comment]
Totally. Come as you are as the song says :)

Thanks!

**Comment by Lawouach** [comment]
Thanks @iggraham for this :)

**Pull request merged**
